# Site settings
title: Graham Troyer-Joy
description: I'm a digital storyteller with a passion for data. #TODO and other stuff


# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
